### ISSUE TITLE
Adding a station that doesn't exist causes TrackAudio to crash

### ISSUE THREAD

**Issue by neilenns** [pierr3/TrackAudio#221] opened 2024-11-18 19:41 UTC
To reproduce:

1. Connect TrackAudio
2. Hit the add button
3. Add `SEA_RND` as a station

Result: TrackAudio crashes
Expected result: No crash, and either an error (preferred) or nothing.

**Comment by neilenns** [comment] 2024-11-18 19:44
Callstack:

```
>	msvcp140d.dll!std::_Xout_of_range(const char * _Message) Line 23	C++
 	trackaudio-afv.node!std::_String_val<std::_Simple_types<char>>::_Xran() Line 463	C++
 	trackaudio-afv.node!std::_String_val<std::_Simple_types<char>>::_Check_offset(const unsigned __int64 _Off) Line 451	C++
 	trackaudio-afv.node!std::string::basic_string<char,std::char_traits<char>,std::allocator<char>>(const std::string & _Right, const unsigned __int64 _Roff, const unsigned __int64 _Count, const std::allocator<char> & _Al) Line 718	C++
 	trackaudio-afv.node!std::string::substr(const unsigned __int64 _Off, const unsigned __int64 _Count) Line 2811	C++
 	trackaudio-afv.node!ns::Station::build(const std::string & callsign, int freqHz) Line 79	C++
 	trackaudio-afv.node!SDK::handleAFVEventForWebsocket(sdk::types::Event event, const std::optional<std::string> & callsign, const std::optional<int> & frequencyHz) Line 145	C++
 	trackaudio-afv.node!RadioHelper::SetRadioState(const std::shared_ptr<SDK> & mApiServer, const RadioState & newState, const std::string & stationCallsign) Line 71	C++
 	trackaudio-afv.node!`anonymous namespace'::AddFrequency(const Napi::CallbackInfo & info) Line 202	C++
 	trackaudio-afv.node!Napi::details::CallbackData<Napi::Boolean (__cdecl*)(Napi::CallbackInfo const &),Napi::Boolean>::Wrapper::__l2::<lambda>() Line 82	C++
 	trackaudio-afv.node!Napi::details::WrapCallback<Napi::Boolean <lambda>(void)>(Napi::details::CallbackData<Napi::Boolean (__cdecl*)(Napi::CallbackInfo const &),Napi::Boolean>::Wrapper::__l2::Napi::Boolean <lambda>(void) callback) Line 61	C++
 	trackaudio-afv.node!Napi::details::CallbackData<Napi::Boolean (__cdecl*)(Napi::CallbackInfo const &),Napi::Boolean>::Wrapper(napi_env__ * env, napi_callback_info__ * info) Line 84	C++
```

**Comment by GeorgeBarlow** [comment] 2024-11-20 09:58
Reproduced the issue and found the problem, invalid stations are still being appended into the radio state store inside afv-native with a frequency value that is not what the TrackAudio SDK is expecting when looking through all the radio states. Need to add some safer handling of these frequency strings we receive from afv-native and also prevent invalid frequencies from being stored within afv-native in the first place.

**Comment by GeorgeBarlow** [comment] 2024-11-20 10:31
Ignore the above, I've done some digging and realised there was some problematic code inside the function that handles AFV events inside `main.cpp` and that `StationDataReceived` event previously looked like this 

```c++
if (eventType == afv_native::ClientEventType::StationDataReceived) {
        if (!stationData || !int1) {
            return;
        }
        bool found = static_cast<bool>(int1);
        
        if (!found) {
            NapiHelpers::sendErrorToElectron("Station not found");
            return;
        }

        std::string callsign = stationData->first;
        unsigned int frequency = stationData->second;

        if (mClient->IsFrequencyActive(frequency)) {
            PLOGW << "StationDataReceived: Frequency " << frequency << " already active, skipping";
            return;
        }

        NapiHelpers::callElectron("StationDataReceived", callsign, std::to_string(frequency));
        MainThreadShared::mApiServer->publishStationAdded(callsign, static_cast<int>(frequency));
    }
    ```
    
The issue is because we were casting a `std::optional<int>` to a `bool` instead of the actual value inside the optional, meaning that we were in essence resolving the state of the boolean to whether or not the optional actually held something, rather than resolving it to the state of the `int` within it. 

Everything should work as expected now.

**Closed by GeorgeBarlow** 2024-11-20 10:31 UTC
Labels: bug

**Comment by pierr3** [comment] 2024-11-20 11:38
Good catch, wonder why it also was not working previously though. Anymore
point against casting.
