### ISSUE TITLE
[8300:1130/200631.952:ERROR:crashpad_client_win.cc(868)] not connected

### ISSUE THREAD

**Issue by Ev1dentSnow** [pierr3/TrackAudio#234] opened 2024-11-30 18:08 UTC
This error occurs when trying to launch the latest version of TrackAudio on Windows. The app will not launch

**Comment by pierr3** [comment] 2024-12-03 15:27
@GeorgeBarlow know what this is?

@Ev1dentSnow any chance you can share the full trace if you have it? Can you also share your version of Windows and your Ptt device, as much info as you can?

**Comment by pierr3** [comment] 2024-12-21 14:44
Duplicate of #240 @Ev1dentSnow can you go into that issue and try the test build to see if that works?

**Closed by pierr3** 2024-12-21 14:44 UTC

**Comment by evidentsnow** [comment] 2024-12-25 20:47
> @GeorgeBarlow know what this is?
> 
> @Ev1dentSnow any chance you can share the full trace if you have it? Can you also share your version of Windows and your Ptt device, as much info as you can?

latest windows 11, Ptt device is keyboard, that is the full trace from cmd
