### ISSUE TITLE
'Always on Top' mode Forces Window to the Back

### ISSUE THREAD

**Issue by wipk10** [pierr3/TrackAudio#90] opened 2024-06-04 15:42 UTC
Pretty self explanatory really, when I select in the settings for TrackAudio to be always on top, it does quite literally the opposite and is forced to the back behind any other windows. When the setting is disabled the TrackAudio window works as expected. 

I've got a little video of how that works here: https://youtu.be/112D8_q26Mk

Otherwise love the software, hope this can be ironed out :)

**Comment by neilenns** [comment] 2024-06-04 16:34
Interesting, I can't reproduce this on my Windows 11 machine.

Does it still happen if you re-launch TrackAudio? Does it happen with any window or just VatSpy?

**Comment by neilenns** [comment] 2024-06-04 17:27
It's possible it's this ancient Electron issue: https://github.com/electron/electron/issues/20933. Fixed in a branch, will open a PR once Pierre merges something else.

**Closed** 2024-06-05 00:18 UTC

**Comment by wipk10** [comment] 2024-06-15 08:57
Hey there, sorry for not getting back to you I've been submerged in travel and work, but whatever you've done seems to have fixed it after downloading the latest version, thanks for the quick fix and help! Lovely software btw, keep up the good work :)
