### ISSUE TITLE
Bring to front or notify on error

### ISSUE THREAD

**Issue by Terminal-Rat** [pierr3/TrackAudio#132] opened 2024-07-09 23:14 UTC
Is it possible to have the app either get focus or flash the taskbar icon if an error occurs? I was controlling and got disconnected from the server but didn't notice until I had tried to call an aircraft multiple times and finally brought the program up to check.

**Comment by neilenns** [comment] 2024-07-10 00:03
There's supposed to be a sound that plays but that's currently not working, see https://github.com/pierr3/TrackAudio/issues/126

**Comment by Terminal-Rat** [comment] 2024-07-10 00:08
> There's supposed to be a sound that plays but that's currently not working, see #126

I saw that after I put this in, but with everything else going on while controlling I'm much less likely to notice an aural cue as opposed to a visual one.

**Comment by pierr3** [comment] 2024-07-10 00:10
You will notice the new sound, duplicate of #126 so will close but will be solved as described in other issue

**Closed by pierr3** 2024-07-10 00:10 UTC

**Comment by neilenns** [comment] 2024-07-10 00:16
Pierre isn't kidding, the new sound is hard to miss 🤣
