### ISSUE TITLE
rxEnd probably missing

### ISSUE THREAD

**Issue by bostjanlaba** [pierr3/TrackAudio#64] opened 2024-05-23 06:34 UTC
Using TrackAudio with Euroscope and KingFuChan's RDF, sometimes the circle marking an aircraft does not disappear after voice transmission at all. This causes all the next circles to be red (audio "collision" on frequency). 

While I cannot check communication between RDF and TrackAudio, I'm guessing RDF does not receive "end of transmission" for that particular aircraft. Any chance to check this out? 

Thank you.

**Comment by KingfuChan** [comment] 2024-05-24 15:08
I can reproduce this issue. I tried with the http SDK and it seems when the transmitting pilot accidentally disconnects from AFV, TrackAudio won't remove it from the transmitting list. Since RDF is using a poll method for now, the circle remains. Hence when I make a GET request to the TrackAudio, it returns the previously disconnected callsign.

**Comment by KingfuChan** [comment] 2024-06-05 08:24
I'm testing it with my latest RDF under development. It seems that when the transmitting station gets disconnected unexpectedly, the kRxEnd message is still not sent properly. 

Now that I add a command line to force a clean-up if such case happens.

Version is 1.1.0-beta.8

**Comment by pierr3** [comment] 2024-07-22 21:44
Fixed in current beta

**Closed by pierr3** 2024-07-22 21:44 UTC
